name: tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: apt-get install
      env:
        DEBIAN_FRONTEND: noninteractive
      run: sudo apt-get update && sudo apt-get install -y npm
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build
